FROM node:16-alpine
ARG NEXT_PUBLIC_BACKEND_HOST
ENV NEXT_PUBLIC_BACKEND_HOST $NEXT_PUBLIC_BACKEND_HOST
ARG NEXT_PUBLIC_BACKEND_HTTP
ENV NEXT_PUBLIC_BACKEND_HTTP $NEXT_PUBLIC_BACKEND_HTTP
WORKDIR /app
COPY . .
RUN npm i
RUN npm run build
EXPOSE 3000
CMD [ "npm", "start" ]