// These styles apply to every route in the application
import './globals.css'
 
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>  
      </head>
      <body>{children}</body>
    </html>
  )
}